
## CS760
## Flight Delay Prediction
## Security Delay Prediction


```{r}
rm(list = ls())
gc(reset=TRUE)
```

```{r}
data2013 = read.csv("2013.csv")
head(data2013)
```




```{r}
dim(data2013)
sort(table(data2013$DEST))
table(data2013$CANCELLATION_CODE)
```




## Only use airport ATL data
```{r}
atl2013_origin = data2013[data2013$ORIGIN=='ATL',]
atl2013_dest = data2013[data2013$DEST=='ATL',]

```

```{r}
atl2013 = atl2013_dest
dim(atl2013)
head(atl2013)
```



```{r}
rm(data2013)
gc(reset=TRUE)
```

```{r}
sum(is.na(atl2013$ARR_DELAY))
atl2013 = atl2013[!is.na(atl2013$ARR_DELAY),]
```

## Date
```{r}
atl2013$flight_date = as.Date(atl2013$FL_DATE,"%Y-%m-%d")
head(atl2013)
```

## month
```{r}
library(lubridate)
atl2013$month = factor(month(atl2013$flight_date))
head(atl2013$month)
```

## wday
```{r}
atl2013$wday = factor(wday(atl2013$flight_date))
head(atl2013$wday)
```


## Hour
```{r}
library(tidyverse)

atl2013 = atl2013 %>% arrange(flight_date, CRS_DEP_TIME)

atl2013$plan_dep_hour = floor(atl2013$CRS_DEP_TIME/100)
atl2013$plan_dep_previous_hour = atl2013$plan_dep_hour-1
head(atl2013, 100)
```






```{r}
atl2013$SECURITY_DELAY_BOOL=!is.na(atl2013$SECURITY_DELAY) & atl2013$SECURITY_DELAY>=15
table(atl2013$SECURITY_DELAY_BOOL)
```



```{r}
pred <- predict(fit_SECURITY, atl2013_SECURITY, type="response")

pred_result = pred>0.5
head(pred_result)

table(atl2013_SECURITY$SECURITY_DELAY_BOOL, pred_result)
sum(pred_result==atl2013_SECURITY$SECURITY_DELAY_BOOL)/length(pred_result)
```





```{r}
atl2013[atl2013$SECURITY_DELAY_BOOL==TRUE,]

table(atl2013[atl2013$SECURITY_DELAY_BOOL==TRUE,]$OP_CARRIER)
```


```{r}
table(atl2013$OP_CARRIER)
```








































